const KurralActionTypes = {
  GET_KURRAL_DATA: 'GET_KURRAL_DATA',
  GET_KURRAL_DATA_SUCCESS: 'GET_KURRAL_DATA_SUCCESS',
  GET_KURRAL_DATA_FAILED: 'GET_KURRAL_DATA_FAILED',
  PAAL_CLICK: 'PAAL_CLICK',
  PAAL_CLICK_SUCCESS: 'PAAL_CLICK_SUCCESS',
  ADIKARAM_CLICK: 'ADIKARAM_CLICK',
  ADIKARAM_CLICK_SUCCESS: 'ADIKARAM_CLICK_SUCCESS',
  KURRAL_CLICK: 'KURRAL_CLICK',
  KURRAL_CLICK_SUCCESS: 'KURRAL_CLICK_SUCCESS',
};

export default KurralActionTypes;